0: 00-weight_count_eBOSS.o catalogue.o functions.o
	g++ 00-weight_count_eBOSS.o catalogue.o functions.o -o 00-weight_count_eBOSS.exe -lm -fopenmp
00-weight_count_eBOSS.o: 00-weight_count_eBOSS.cpp
	g++ -c 00-weight_count_eBOSS.cpp -lm -fopenmp


1: 01-comp_DD_eBOSS_llist.o catalogue.o functions.o
	g++ 01-comp_DD_eBOSS_llist.o catalogue.o functions.o -o 01-comp_DD_eBOSS_llist.exe -lm -fopenmp
01-comp_DD_eBOSS_llist.o: 01-comp_DD_eBOSS_llist.cpp
	g++ -c 01-comp_DD_eBOSS_llist.cpp -lm -fopenmp


2: 02-comp_DR_eBOSS_llist.o catalogue.o functions.o
	g++ 02-comp_DR_eBOSS_llist.o catalogue.o functions.o -o 02-comp_DR_eBOSS_llist.exe -lm -fopenmp
02-comp_DR_eBOSS_llist.o: 02-comp_DR_eBOSS_llist.cpp
	g++ -c 02-comp_DR_eBOSS_llist.cpp -lm -fopenmp


3: 03-comp_RR_eBOSS_llist.o catalogue.o functions.o
	g++ 03-comp_RR_eBOSS_llist.o catalogue.o functions.o -o 03-comp_RR_eBOSS_llist.exe -lm -fopenmp
03-comp_RR_eBOSS_llist.o: 03-comp_RR_eBOSS_llist.cpp
	g++ -c 03-comp_RR_eBOSS_llist.cpp -lm -fopenmp


4: 04-comp_DD_eBOSS_proj_llist.o catalogue.o functions.o
	g++ 04-comp_DD_eBOSS_proj_llist.o catalogue.o functions.o -o 04-comp_DD_eBOSS_proj_llist.exe -lm -fopenmp
04-comp_DD_eBOSS_proj_llist.o: 04-comp_DD_eBOSS_proj_llist.cpp
	g++ -c 04-comp_DD_eBOSS_proj_llist.cpp -lm -fopenmp


5: 05-comp_DR_eBOSS_proj_llist.o catalogue.o functions.o
	g++ 05-comp_DR_eBOSS_proj_llist.o catalogue.o functions.o -o 05-comp_DR_eBOSS_proj_llist.exe -lm -fopenmp
05-comp_DR_eBOSS_proj_llist.o: 05-comp_DR_eBOSS_proj_llist.cpp
	g++ -c 05-comp_DR_eBOSS_proj_llist.cpp -lm -fopenmp


6: 06-comp_RR_eBOSS_proj_llist.o catalogue.o functions.o
	g++ 06-comp_RR_eBOSS_proj_llist.o catalogue.o functions.o -o 06-comp_RR_eBOSS_proj_llist.exe -lm -fopenmp
06-comp_RR_eBOSS_proj_llist.o: 06-comp_RR_eBOSS_proj_llist.cpp
	g++ -c 06-comp_RR_eBOSS_proj_llist.cpp -lm -fopenmp


7: 07-comp_DD_eBOSS_llist_pip.o catalogue.o functions.o
	g++ 07-comp_DD_eBOSS_llist_pip.o catalogue.o functions.o -o 07-comp_DD_eBOSS_llist_pip.exe -lm -fopenmp
07-comp_DD_eBOSS_llist_pip.o: 07-comp_DD_eBOSS_llist_pip.cpp
	g++ -c 07-comp_DD_eBOSS_llist_pip.cpp -lm -fopenmp


8: 08-comp_DR_eBOSS_llist_pip.o catalogue.o functions.o
	g++ 08-comp_DR_eBOSS_llist_pip.o catalogue.o functions.o -o 08-comp_DR_eBOSS_llist_pip.exe -lm -fopenmp
08-comp_DR_eBOSS_llist_pip.o: 08-comp_DR_eBOSS_llist_pip.cpp
	g++ -c 08-comp_DR_eBOSS_llist_pip.cpp -lm -fopenmp


9: 09-comp_DD_eBOSS_proj_llist_pip.o catalogue.o functions.o
	g++ 09-comp_DD_eBOSS_proj_llist_pip.o catalogue.o functions.o -o 09-comp_DD_eBOSS_proj_llist_pip.exe -lm -fopenmp
09-comp_DD_eBOSS_proj_llist_pip.o: 09-comp_DD_eBOSS_proj_llist_pip.cpp
	g++ -c 09-comp_DD_eBOSS_proj_llist_pip.cpp -lm -fopenmp


10: 10-comp_DR_eBOSS_proj_llist_pip.o catalogue.o functions.o
	g++ 10-comp_DR_eBOSS_proj_llist_pip.o catalogue.o functions.o -o 10-comp_DR_eBOSS_proj_llist_pip.exe -lm -fopenmp
10-comp_DR_eBOSS_proj_llist_pip.o: 10-comp_DR_eBOSS_proj_llist_pip.cpp
	g++ -c 10-comp_DR_eBOSS_proj_llist_pip.cpp -lm -fopenmp


11: 11-comp_DD_eBOSS_llist_jk.o catalogue.o functions.o
	g++ 11-comp_DD_eBOSS_llist_jk.o catalogue.o functions.o -o 11-comp_DD_eBOSS_llist_jk.exe -lm -fopenmp
11-comp_DD_eBOSS_llist_jk.o: 11-comp_DD_eBOSS_llist_jk.cpp
	g++ -c 11-comp_DD_eBOSS_llist_jk.cpp -lm -fopenmp


12: 12-comp_DR_eBOSS_llist_jk.o catalogue.o functions.o
	g++ 12-comp_DR_eBOSS_llist_jk.o catalogue.o functions.o -o 12-comp_DR_eBOSS_llist_jk.exe -lm -fopenmp
12-comp_DR_eBOSS_llist_jk.o: 12-comp_DR_eBOSS_llist_jk.cpp
	g++ -c 12-comp_DR_eBOSS_llist_jk.cpp -lm -fopenmp


13: 13-comp_RR_eBOSS_llist_jk.o catalogue.o functions.o
	g++ 13-comp_RR_eBOSS_llist_jk.o catalogue.o functions.o -o 13-comp_RR_eBOSS_llist_jk.exe -lm -fopenmp
13-comp_RR_eBOSS_llist_jk.o: 13-comp_RR_eBOSS_llist_jk.cpp
	g++ -c 13-comp_RR_eBOSS_llist_jk.cpp -lm -fopenmp


14: 14-comp_DD_eBOSS_proj_llist_jk.o catalogue.o functions.o
	g++ 14-comp_DD_eBOSS_proj_llist_jk.o catalogue.o functions.o -o 14-comp_DD_eBOSS_proj_llist_jk.exe -lm -fopenmp
14-comp_DD_eBOSS_proj_llist_jk.o: 14-comp_DD_eBOSS_proj_llist_jk.cpp
	g++ -c 14-comp_DD_eBOSS_proj_llist_jk.cpp -lm -fopenmp


15: 15-comp_DR_eBOSS_proj_llist_jk.o catalogue.o functions.o
	g++ 15-comp_DR_eBOSS_proj_llist_jk.o catalogue.o functions.o -o 15-comp_DR_eBOSS_proj_llist_jk.exe -lm -fopenmp
15-comp_DR_eBOSS_proj_llist_jk.o: 15-comp_DR_eBOSS_proj_llist_jk.cpp
	g++ -c 15-comp_DR_eBOSS_proj_llist_jk.cpp -lm -fopenmp


16: 16-comp_RR_eBOSS_proj_llist_jk.o catalogue.o functions.o
	g++ 16-comp_RR_eBOSS_proj_llist_jk.o catalogue.o functions.o -o 16-comp_RR_eBOSS_proj_llist_jk.exe -lm -fopenmp
16-comp_RR_eBOSS_proj_llist_jk.o: 16-comp_RR_eBOSS_proj_llist_jk.cpp
	g++ -c 16-comp_RR_eBOSS_proj_llist_jk.cpp -lm -fopenmp


17: 17-comp_DD_eBOSS_llist_mock.o catalogue.o functions.o
	g++ 17-comp_DD_eBOSS_llist_mock.o catalogue.o functions.o -o 17-comp_DD_eBOSS_llist_mock.exe -lm -fopenmp
17-comp_DD_eBOSS_llist_mock.o: 17-comp_DD_eBOSS_llist_mock.cpp
	g++ -c 17-comp_DD_eBOSS_llist_mock.cpp -lm -fopenmp


18: 18-comp_DR_eBOSS_llist_mock.o catalogue.o functions.o
	g++ 18-comp_DR_eBOSS_llist_mock.o catalogue.o functions.o -o 18-comp_DR_eBOSS_llist_mock.exe -lm -fopenmp
18-comp_DR_eBOSS_llist_mock.o: 18-comp_DR_eBOSS_llist_mock.cpp
	g++ -c 18-comp_DR_eBOSS_llist_mock.cpp -lm -fopenmp


19: 19-comp_RR_eBOSS_llist_mock.o catalogue.o functions.o
	g++ 19-comp_RR_eBOSS_llist_mock.o catalogue.o functions.o -o 19-comp_RR_eBOSS_llist_mock.exe -lm -fopenmp
19-comp_RR_eBOSS_llist_mock.o: 19-comp_RR_eBOSS_llist_mock.cpp
	g++ -c 19-comp_RR_eBOSS_llist_mock.cpp -lm -fopenmp


20: 20-comp_DD_eBOSS_proj_llist_mock.o catalogue.o functions.o
	g++ 20-comp_DD_eBOSS_proj_llist_mock.o catalogue.o functions.o -o 20-comp_DD_eBOSS_proj_llist_mock.exe -lm -fopenmp
20-comp_DD_eBOSS_proj_llist_mock.o: 20-comp_DD_eBOSS_proj_llist_mock.cpp
	g++ -c 20-comp_DD_eBOSS_proj_llist_mock.cpp -lm -fopenmp


21: 21-comp_DR_eBOSS_proj_llist_mock.o catalogue.o functions.o
	g++ 21-comp_DR_eBOSS_proj_llist_mock.o catalogue.o functions.o -o 21-comp_DR_eBOSS_proj_llist_mock.exe -lm -fopenmp
21-comp_DR_eBOSS_proj_llist_mock.o: 21-comp_DR_eBOSS_proj_llist_mock.cpp
	g++ -c 21-comp_DR_eBOSS_proj_llist_mock.cpp -lm -fopenmp


22: 22-comp_RR_eBOSS_proj_llist_mock.o catalogue.o functions.o
	g++ 22-comp_RR_eBOSS_proj_llist_mock.o catalogue.o functions.o -o 22-comp_RR_eBOSS_proj_llist_mock.exe -lm -fopenmp
22-comp_RR_eBOSS_proj_llist_mock.o: 22-comp_RR_eBOSS_proj_llist_mock.cpp
	g++ -c 22-comp_RR_eBOSS_proj_llist_mock.cpp -lm -fopenmp


23: 23-norm_count_DD_pip.o catalogue.o functions.o
	g++ 23-norm_count_DD_pip.o catalogue.o functions.o -o 23-norm_count_DD_pip.exe -lm -fopenmp
23-norm_count_DD_pip.o: 23-norm_count_DD_pip.cpp
	g++ -c 23-norm_count_DD_pip.cpp -lm -fopenmp


24: 24-comp_DD_eBOSS_ang.o catalogue.o functions.o
	g++ 24-comp_DD_eBOSS_ang.o catalogue.o functions.o -o 24-comp_DD_eBOSS_ang.exe -lm -fopenmp
24-comp_DD_eBOSS_ang.o: 24-comp_DD_eBOSS_ang.cpp
	g++ -c 24-comp_DD_eBOSS_ang.cpp -lm -fopenmp


25: 25-comp_DR_eBOSS_ang.o catalogue.o functions.o
	g++ 25-comp_DR_eBOSS_ang.o catalogue.o functions.o -o 25-comp_DR_eBOSS_ang.exe -lm -fopenmp
25-comp_DR_eBOSS_ang.o: 25-comp_DR_eBOSS_ang.cpp
	g++ -c 25-comp_DR_eBOSS_ang.cpp -lm -fopenmp


26: 26-norm_count_DR_pip.o catalogue.o functions.o
	g++ 26-norm_count_DR_pip.o catalogue.o functions.o -o 26-norm_count_DR_pip.exe -lm -fopenmp
26-norm_count_DR_pip.o: 26-norm_count_DR_pip.cpp
	g++ -c 26-norm_count_DR_pip.cpp -lm -fopenmp


27: 27-norm_count_RR_pip.o catalogue.o functions.o
	g++ 27-norm_count_RR_pip.o catalogue.o functions.o -o 27-norm_count_RR_pip.exe -lm -fopenmp
27-norm_count_RR_pip.o: 27-norm_count_RR_pip.cpp
	g++ -c 27-norm_count_RR_pip.cpp -lm -fopenmp


28: 28-norm_count_DD_ang.o catalogue.o functions.o
	g++ 28-norm_count_DD_ang.o catalogue.o functions.o -o 28-norm_count_DD_ang.exe -lm -fopenmp
28-norm_count_DD_ang.o: 28-norm_count_DD_ang.cpp
	g++ -c 28-norm_count_DD_ang.cpp -lm -fopenmp


29: 29-norm_count_DR_ang.o catalogue.o functions.o
	g++ 29-norm_count_DR_ang.o catalogue.o functions.o -o 29-norm_count_DR_ang.exe -lm -fopenmp
29-norm_count_DR_ang.o: 29-norm_count_DR_ang.cpp
	g++ -c 29-norm_count_DR_ang.cpp -lm -fopenmp


30: 30-norm_count_DD_pip_cross.o catalogue.o functions.o
	g++ 30-norm_count_DD_pip_cross.o catalogue.o functions.o -o 30-norm_count_DD_pip_cross.exe -lm -fopenmp
30-norm_count_DD_pip_cross.o: 30-norm_count_DD_pip_cross.cpp
	g++ -c 30-norm_count_DD_pip_cross.cpp -lm -fopenmp


31: 31-norm_count_DD_pip_cross_approx.o catalogue.o functions.o
	g++ 31-norm_count_DD_pip_cross_approx.o catalogue.o functions.o -o 31-norm_count_DD_pip_cross_approx.exe -lm -fopenmp
31-norm_count_DD_pip_cross_approx.o: 31-norm_count_DD_pip_cross_approx.cpp
	g++ -c 31-norm_count_DD_pip_cross_approx.cpp -lm -fopenmp


32: 32-calc_z_eff_pip.o catalogue.o functions.o
	g++ 32-calc_z_eff_pip.o catalogue.o functions.o -o 32-calc_z_eff_pip.exe -lm -fopenmp
32-calc_z_eff_pip.o: 32-calc_z_eff_pip.cpp
	g++ -c 32-calc_z_eff_pip.cpp -lm -fopenmp


catalogue.o: classes/catalogue.cpp
	g++ -c classes/catalogue.cpp -Wall -Werror -lm
functions.o: classes/functions.cpp
	g++ -c classes/functions.cpp -Wall -Werror -lm
